[package]
name = "world-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.8.2"
dot_vox = "5.1.0"

[patch.crates-io]
dot_vox = { path = "./dot_vox" }
